version: "3.8"
services:
    puffy-db:
        image: mysql:latest
        restart: always
        ports:
        - '3306:3306'
        environment:
          MYSQL_DATABASE: ${DB_NAME}
          MYSQL_USER: ${DB_USERNAME}
          MYSQL_PASSWORD: ${DB_SEC}
          MYSQL_ROOT_PASSWORD: ${DB_SEC}
        volumes:
          - puffy-db:/var/lib/mysql
          - ./puffy_script_v2.sql:/docker-entrypoint-initdb.d/schema.sql
    puffy-redis:
        image: redis:7.0-alpine
        restart: always
        ports:
          - '6379:6379'
        command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_SEC}
    puffy:
        container_name: puffy
        build: ./Puffy
        depends_on:
          - puffy-db
          - puffy-redis
        ports:
          - '3030:3030'
        links:
          - puffy-db
          - puffy-redis
volumes:
  puffy-db:
    driver: local