-- MySQL Script generated by MySQL Workbench
-- Wed Aug 18 20:04:44 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema puffy_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `puffy_db` ;

-- -----------------------------------------------------
-- Schema puffy_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `puffy_db` DEFAULT CHARACTER SET utf8 ;
USE `puffy_db` ;

-- -----------------------------------------------------
-- Table `puffy_db`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `puffy_db`.`user` ;

CREATE TABLE IF NOT EXISTS `puffy_db`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(50) NOT NULL,
  `last_name` VARCHAR(100) NOT NULL,
  `mobile` VARCHAR(15) NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `admin` TINYINT(1) NOT NULL,
  `avatar` VARCHAR(100) NULL,
  `last_login` DATETIME NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `email` USING BTREE (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `puffy_db`.`address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `puffy_db`.`address` ;

CREATE TABLE IF NOT EXISTS `puffy_db`.`address` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `line1` VARCHAR(250) NOT NULL,
  `line2` VARCHAR(100) NULL,
  `city` VARCHAR(250) NOT NULL,
  `state` VARCHAR(250) NOT NULL,
  `country` VARCHAR(100) NOT NULL,
  `zip` INT(5) NOT NULL,
  `user_id` INT NOT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_address_user_idx` (`user_id` ASC),
  CONSTRAINT `fk_address_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `puffy_db`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `puffy_db`.`product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `puffy_db`.`product` ;

CREATE TABLE IF NOT EXISTS `puffy_db`.`product` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(250) NOT NULL,
  `description` TEXT NOT NULL,
  `price` DOUBLE NOT NULL,
  `quantity` INT NOT NULL,
  `discount` FLOAT NULL,
  `size` TINYINT(5) NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `puffy_db`.`category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `puffy_db`.`category` ;

CREATE TABLE IF NOT EXISTS `puffy_db`.`category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `puffy_db`.`product_images`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `puffy_db`.`product_images` ;

CREATE TABLE IF NOT EXISTS `puffy_db`.`product_images` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `url` VARCHAR(250) NULL,
  `main` TINYINT(1) NOT NULL,
  `product_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_product_images_product1_idx` (`product_id` ASC),
  CONSTRAINT `fk_product_images_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `puffy_db`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `puffy_db`.`product_category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `puffy_db`.`product_category` ;

CREATE TABLE IF NOT EXISTS `puffy_db`.`product_category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `product_id` INT NOT NULL,
  `category_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_product_has_category_category1_idx` (`category_id` ASC),
  INDEX `fk_product_has_category_product1_idx` (`product_id` ASC),
  CONSTRAINT `fk_product_has_category_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `puffy_db`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_has_category_category1`
    FOREIGN KEY (`category_id`)
    REFERENCES `puffy_db`.`category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `puffy_db`.`cart`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `puffy_db`.`cart` ;

CREATE TABLE IF NOT EXISTS `puffy_db`.`cart` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `sessionId` VARCHAR(100) NULL,
  `token` VARCHAR(150) NULL,
  `status` CHAR(10) NULL,
  `user_id` INT NOT NULL,
  `address_id` INT NOT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_cart_user1_idx` (`user_id` ASC),
  INDEX `fk_cart_address1_idx` (`address_id` ASC),
  CONSTRAINT `fk_cart_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `puffy_db`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cart_address1`
    FOREIGN KEY (`address_id`)
    REFERENCES `puffy_db`.`address` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `puffy_db`.`product_cart`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `puffy_db`.`product_cart` ;

CREATE TABLE IF NOT EXISTS `puffy_db`.`product_cart` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `product_id` INT NOT NULL,
  `cart_id` INT NOT NULL,
  PRIMARY KEY (`product_id`, `cart_id`),
  INDEX `fk_product_has_cart_cart1_idx` (`cart_id` ASC),
  INDEX `fk_product_has_cart_product1_idx` (`product_id` ASC),
  CONSTRAINT `fk_product_has_cart_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `puffy_db`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_has_cart_cart1`
    FOREIGN KEY (`cart_id`)
    REFERENCES `puffy_db`.`cart` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `puffy_db`.`order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `puffy_db`.`order` ;

CREATE TABLE IF NOT EXISTS `puffy_db`.`order` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `sessionId` VARCHAR(100) NULL,
  `token` VARCHAR(100) NULL,
  `status` CHAR(10) NULL,
  `subtotal` FLOAT NOT NULL,
  `discount` FLOAT NULL,
  `tax` FLOAT NOT NULL,
  `shipping` FLOAT NOT NULL,
  `total` FLOAT NOT NULL,
  `promo` VARCHAR(45) NULL,
  `promo_discount` FLOAT NULL,
  `grandTotal` FLOAT NOT NULL,
  `user_id` INT NOT NULL,
  `address_id` INT NOT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_order_user1_idx` (`user_id` ASC),
  INDEX `fk_order_address1_idx` (`address_id` ASC),
  CONSTRAINT `fk_order_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `puffy_db`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_address1`
    FOREIGN KEY (`address_id`)
    REFERENCES `puffy_db`.`address` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


-- DATOS DE PRUEBA

INSERT INTO `puffy_db`.`user` (`first_name`, `last_name`, `mobile`, `email`, `password`, `admin`, `avatar`) VALUES 
('Gabo', 'espinosa', '23425232', 'gabo@email.com', '6Rj/QyOBHrKfaEVTPVgRseC0J8PwkscAUV3jM.jBx7IKn11IpP01q', '1', '/images/avatars/default.jpg'),
('Montse', 'Olmedo', '35643552', 'montse@email.com', 'bn1btTQWWgBrX/IK5vjxzudBwkSvUeU33jrt09ES6lV5BatBxebee', '0', '/images/avatars/default.jpg');

INSERT INTO `puffy_db`.`address` (`line1`, `line2`, `city`, `state`, `country`, `zip`, `user_id`) VALUES 
('Calle Norte 1', 'Colonia Juarez', 'Gustavo A Madero', 'CDMX', 'MX', '06600', '1'), 
('Calle Sur1', 'Colonia Hidalgo', 'Juarez', 'Chihuahua', 'MX', '58940', '2');

INSERT INTO `puffy_db`.`order` (`sessionId`, `token`, `status`, `subtotal`, `discount`, `tax`, `shipping`, `total`, `promo`, `promo_discount`, `grandTotal`, `user_id`, `address_id`) VALUES 
('1', 'fgsdgsdgd', '0', '10.2', '0.1', '0.16', '10.0', '100.0', 'asdfas', '0.1', '90.0', '1', '1'), 
('2', 'asdfas', '1', '99.2', '0.2', '0.16', '100.0', '200.0', 'fsdfs', '0.0', '200.0', '2', '2'), 
('3', 'asfasf', '0', '500.0', '0.05', '0.15', '150.0', '350.0', 'adfs', '0.2', '300.0', '1', '1');
