apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
data:
  redis.conf: |
    masterauth ${REDIS_SEC}
    requirepass ${REDIS_SEC}


apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: cache-local-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain 


# PersistentVolume for local run
apiVersion: v1
kind: PersistentVolume
metadata:
  name: cache-pv
spec:
  capacity:
    storage: 1Gi
  storageClassName: cache-local-storage
  accessModes:
    - ReadWriteOnce
  local:
    path: /tmp/data/cache
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - docker-desktop

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cache-pvc
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: cache-local-storage
  resources:
    requests:
      storage: 1Gi