apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: cache-local-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
reclaimPolicy: Delete

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: cache-local-pv0
spec:
  storageClassName: cache-local-storage
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/storage/data1"

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: cache-local-pv1
spec:
  storageClassName: cache-local-storage
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/storage/data2"

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: cache-local-pv2
spec:
  storageClassName: cache-local-storage
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/storage/data3"