apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
spec:
  replicas: 1
  minReadySeconds: 10
  selector:
      matchLabels:
        app: database
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
      - image: mysql:8
        name: database
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: DB_ROOT_SEC
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: DB_NAME
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: DB_USERNAME
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: DB_SEC
        ports:
        - containerPort: 3306
          name: database
          protocol: TCP
        volumeMounts:
        - name: database-local-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: database-local-storage
        persistentVolumeClaim:
          claimName: database-pvc