apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: database-local-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: database-pv
spec:
  storageClassName: database-local-storage
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: /tmp/data/db

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-pvc
spec:
  storageClassName: database-local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi