apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: main-entrypoint
spec:
  rules:
  - http:
      paths:
      - path: /dashboard
        pathType: Prefix
        backend:
          service:
            name: dashboard-lb
            port:
              number: 3031              
      - path: /
        pathType: Prefix
        backend:
          service:
            name: backend-lb
            port:
              number: 3030
