GET http://localhost:3030/api/users HTTP/1.1

###

GET http://localhost:3030/api/users/3 HTTP/1.1

###

GET http://localhost:3030/api/products/ HTTP/1.1

###

GET http://localhost:3030/api/products/1 HTTP/1.1

###

GET http://localhost:3030/api/products/sales HTTP/1.1

###

GET http://localhost:3030/api/categories HTTP/1.1