// API TEST FOR USERS
// List all users
GET  http://localhost:3030/api/users/ HTTP/1.1
###
// List a user
GET  http://localhost:3030/api/users/1 HTTP/1.1
###
// Create user
POST http://localhost:3030/api/users/ HTTP/1.1
content-type: application/json

{
    "firstName": "Prueba",
    "lastName": "1septiembre",
    "mobile": "12412341",
    "email": "prueba@correo.com",
    "password": "6Rj/QyOBHrKfaEVTPVgRseC0J8PwkscAUV3jM.jBx7IKn11IpP01q",
    "admin": 0
}
###
// Edit user
PUT http://localhost:3030/api/users/6 HTTP/1.1
content-type: application/json

{
    "firstName": "Modificado",
    "lastName": "user",
    "mobile": "234",
    "admin": 0
}
###
// Remove user
DELETE  http://localhost:3030/api/users/5 HTTP/1.1